name: feed_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  chewie: ^1.7.0
  video_player: ^2.8.2


  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  percent_indicator: ^4.2.3 # or the latest version


flutter:
  uses-material-design: true

assets:
    - assets/images/reel.png
   # - assets/videos/fisg.mp4

fonts:    
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
 