name: feed_application
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  chewie: ^1.7.0
  reels_viewer: ^2.0.0
  percent_indicator: ^4.2.3
  path_provider: ^2.1.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

#assets:
   # - assets/images/reel.png
   # - assets/videos/fisg.mp4

fonts:    
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
 